#!/usr/bin/env python3
"""
VeriGuard Build Script

Usage:
    ./build.py                          # Build (default)
    ./build.py build                    # Build Ada crates and ESP-IDF firmware
    ./build.py clean                    # Clean both Ada crates and ESP-IDF
    ./build.py clean build              # Chain: clean then build
    ./build.py build --idf monitor      # Build, then run idf.py monitor
    ./build.py build --idf -p /dev/ttyUSB0 flash  # Build, then flash to specific port
    ./build.py build --alr --release    # Build with --release flag to alr
    ./build.py keygen                   # Generate test keypairs (ESP32 + Python)
    ./build.py keygen --psk             # Generate keypairs with a pre-shared key

Flags:
    --alr <args...>     Pass arguments to alr build/clean commands
    --idf <args...>     Pass arguments to idf.py after build/clean
    --psk               Include a random 32-byte pre-shared key (keygen only)
"""

import os
import sys
import subprocess
from pathlib import Path

# Configuration
SCRIPT_DIR = Path(__file__).parent.absolute()
ADA_CRATES = ["wireguard"]  # Single consolidated crate
VALID_COMMANDS = {"build", "clean", "keygen"}


def generate_keypairs(with_psk=False):
    """Generate two X25519 keypairs (ESP32 + Python) and optional PSK.

    Outputs:
      1. Python module at tests/integration/test_keys.py
      2. ESP32 key hex printed to stdout for sdkconfig
    """
    from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey

    esp32_priv = X25519PrivateKey.generate()
    esp32_pub = esp32_priv.public_key().public_bytes_raw()
    esp32_priv_bytes = esp32_priv.private_bytes_raw()

    python_priv = X25519PrivateKey.generate()
    python_pub = python_priv.public_key().public_bytes_raw()
    python_priv_bytes = python_priv.private_bytes_raw()

    psk_bytes = os.urandom(32) if with_psk else bytes(32)

    # ── Write Python module ──────────────────────────────────────────
    keys_file = SCRIPT_DIR / "tests" / "integration" / "test_keys.py"
    lines = [
        '"""Fixed test keypairs for integration testing.',
        "",
        "Auto-generated by build.py keygen — do not edit by hand.",
        '"""',
        "",
        "from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey",
        "",
        "",
        f'ESP32_PRIVATE_HEX = "{esp32_priv_bytes.hex()}"',
        f'ESP32_PUBLIC_HEX  = "{esp32_pub.hex()}"',
        "",
        f'PYTHON_PRIVATE_HEX = "{python_priv_bytes.hex()}"',
        f'PYTHON_PUBLIC_HEX  = "{python_pub.hex()}"',
        "",
        f'PRESHARED_KEY_HEX = "{psk_bytes.hex()}"',
        "",
        "",
        "# ── Convenience helpers ──────────────────────────────────────────",
        "",
        "def esp32_private_key() -> X25519PrivateKey:",
        '    """ESP32 static private key as an X25519PrivateKey object."""',
        "    return X25519PrivateKey.from_private_bytes(bytes.fromhex(ESP32_PRIVATE_HEX))",
        "",
        "",
        "def python_private_key() -> X25519PrivateKey:",
        '    """Python-side static private key as an X25519PrivateKey object."""',
        "    return X25519PrivateKey.from_private_bytes(bytes.fromhex(PYTHON_PRIVATE_HEX))",
        "",
        "",
        "def esp32_public() -> bytes:",
        '    """ESP32 static public key as raw bytes."""',
        "    return bytes.fromhex(ESP32_PUBLIC_HEX)",
        "",
        "",
        "def python_public() -> bytes:",
        '    """Python-side static public key as raw bytes."""',
        "    return bytes.fromhex(PYTHON_PUBLIC_HEX)",
        "",
        "",
        "def preshared_key() -> bytes:",
        '    """Pre-shared key as raw bytes (all-zero if no PSK)."""',
        "    return bytes.fromhex(PRESHARED_KEY_HEX)",
        "",
    ]
    keys_file.write_text("\n".join(lines))
    print(f"  Wrote {keys_file.relative_to(SCRIPT_DIR)}")

    # ── Print ESP32 keys to stdout ───────────────────────────────────
    print("\n" + "=" * 60)
    print("  ESP32 sdkconfig values (paste into sdkconfig or menuconfig)")
    print("=" * 60)
    print(f'CONFIG_WG_STATIC_PRIVATE_KEY="{esp32_priv_bytes.hex()}"')
    print(f'CONFIG_WG_PEER_PUBLIC_KEY="{python_pub.hex()}"')
    if with_psk:
        print(f'CONFIG_WG_PRESHARED_KEY="{psk_bytes.hex()}"')
    else:
        print('CONFIG_WG_PRESHARED_KEY=""')
    print("=" * 60)

    # Also print the Python side for reference
    print("\n  Python-side keys (already saved in test_keys.py):")
    print(f"  Private: {python_priv_bytes.hex()}")
    print(f"  Public:  {python_pub.hex()}")
    print(f"  ESP32 public (peer for Python): {esp32_pub.hex()}")
    if with_psk:
        print(f"  PSK:     {psk_bytes.hex()}")
    print()

    return True


def check_idf_path():
    """Verify IDF_PATH environment variable is set."""
    if not os.environ.get("IDF_PATH"):
        print("ERROR: IDF_PATH not set. Run: source /opt/esp-idf/export.sh")
        sys.exit(1)


def run_command(cmd, cwd=None, description=""):
    """Execute a shell command with output streamed to terminal."""
    try:
        if description:
            print(f"\n  {description}...")
        
        result = subprocess.run(
            cmd,
            shell=True,
            cwd=cwd or SCRIPT_DIR,
        )
        
        return result.returncode == 0
    except Exception as e:
        print(f"ERROR: {e}")
        return False


def run_command_interactive(cmd, cwd=None, description=""):
    """Execute a shell command interactively (output to terminal)."""
    try:
        if description:
            print(f"\n{description}...\n")
        
        result = subprocess.run(
            cmd,
            shell=True,
            cwd=cwd or SCRIPT_DIR,
        )
        
        return result.returncode == 0
    except Exception as e:
        print(f"ERROR: {e}")
        return False


def clean_ada_crates(alr_args=""):
    """Clean all Ada crates."""
    print("\n[1/2] Cleaning Ada crates with Alire...")
    all_success = True
    
    for crate in ADA_CRATES:
        crate_dir = SCRIPT_DIR / crate
        cmd = f"alr clean {alr_args}".strip()
        if not run_command(cmd, cwd=crate_dir, description=f"Cleaning {crate}"):
            all_success = False
    
    return all_success


def clean_idf(idf_args=""):
    """Clean ESP-IDF build."""
    print("\n[2/2] Cleaning ESP-IDF firmware...")
    cmd = f"idf.py fullclean {idf_args}".strip()
    return run_command(cmd, description="Cleaning ESP-IDF")


def build_ada_crates(alr_args=""):
    """Build all Ada crates."""
    print("\n[1/2] Building Ada crates with Alire...")
    all_success = True
    
    for crate in ADA_CRATES:
        crate_dir = SCRIPT_DIR / crate
        cmd = f"alr build --release {alr_args}".strip()
        if not run_command(cmd, cwd=crate_dir, description=f"Building {crate}"):
            all_success = False
    
    return all_success


def build_idf(idf_args=""):
    """Build ESP-IDF firmware."""
    print("\n[2/2] Building ESP-IDF firmware...")
    cmd = f"idf.py build {idf_args}".strip()
    return run_command(cmd, description="Building firmware")


def execute_command(cmd, alr_args="", idf_args="", psk=False):
    """Execute a single command."""
    if cmd == "clean":
        return clean_ada_crates(alr_args) and clean_idf(idf_args)
    elif cmd == "build":
        return build_ada_crates(alr_args) and build_idf(idf_args)
    elif cmd == "keygen":
        return generate_keypairs(with_psk=psk)
    else:
        return False


def execute_idf_command(idf_args):
    """Execute a standalone idf.py command interactively."""
    cmd = f"idf.py {idf_args}".strip()
    return run_command_interactive(cmd, description="Running idf.py")


def print_header(title):
    """Print a formatted header."""
    print("\n" + "=" * 42)
    print(f"{title.center(42)}")
    print("=" * 42)


def print_footer(success):
    """Print a formatted footer."""
    print("\n" + "=" * 42)
    if success:
        print(f"{'Build Complete!'.center(42)}")
        print(f"{'Firmware: build/VeriGuard.elf'.center(42)}")
    else:
        print(f"{'Build Failed!'.center(42)}")
    print("=" * 42 + "\n")


def main():
    """Main entry point."""
    
    # Parse arguments - flags apply only to commands that follow them
    args = sys.argv[1:]
    
    if not args:
        args = ["build"]
    
    commands = []  # List of (command, alr_args, idf_args)
    idf_command_after = ""
    psk_flag = False
    
    i = 0
    current_alr_args = ""
    current_idf_args = ""
    
    while i < len(args):
        arg = args[i]
        
        if arg == "--psk":
            psk_flag = True
            i += 1
            continue
        
        elif arg == "--alr":
            # Collect alr args until --idf or next command
            alr_parts = []
            i += 1
            while i < len(args) and args[i] not in VALID_COMMANDS and args[i] != "--idf":
                alr_parts.append(args[i])
                i += 1
            current_alr_args = " ".join(alr_parts)
            continue
        
        elif arg == "--idf":
            # Collect all remaining args as idf args
            idf_parts = []
            i += 1
            while i < len(args):
                idf_parts.append(args[i])
                i += 1
            idf_command_after = " ".join(idf_parts)
            break
        
        elif arg in VALID_COMMANDS:
            # Add command with current flag context
            commands.append((arg, current_alr_args, current_idf_args))
            # Reset alr args for next command (but keep idf args if any)
            current_alr_args = ""
            i += 1
        
        else:
            print(f"ERROR: Unknown argument '{arg}'")
            print(f"\nUsage: {Path(__file__).name} [command ...] [--alr args...] [--idf args...]")
            print("\nValid commands: build, clean, keygen")
            print("\nExamples:")
            print(f"  {Path(__file__).name} build")
            print(f"  {Path(__file__).name} clean build --alr --release")
            print(f"  {Path(__file__).name} build --idf monitor")
            print(f"  {Path(__file__).name} clean build --alr --release --idf monitor")
            print(f"  {Path(__file__).name} keygen")
            print(f"  {Path(__file__).name} keygen --psk")
            sys.exit(1)
    
    if not commands:
        commands = [("build", "", "")]
    
    # Only require IDF_PATH for build/clean (not keygen)
    needs_idf = any(cmd[0] in ("build", "clean") for cmd in commands) or idf_command_after
    if needs_idf:
        check_idf_path()
    
    # Determine action description
    action = " → ".join(cmd[0] for cmd in commands)
    extra = ""
    if idf_command_after:
        extra = f" → idf.py {idf_command_after}"
    
    print_header(f"VeriGuard {action.title()}{extra}")
    
    # Execute commands in sequence
    success = True
    for cmd, alr_args, idf_args in commands:
        if not execute_command(cmd, alr_args, idf_args, psk=psk_flag):
            success = False
            break
    
    # Execute idf.py command if specified
    if success and idf_command_after:
        if not execute_idf_command(idf_command_after):
            success = False
    
    print_footer(success)
    
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()

