#!/usr/bin/env python3
"""
VeriGuard Build Script

Usage:
    ./build.py                                    # Build (default: release)
    ./build.py build                              # Build Ada crates and ESP-IDF firmware
    ./build.py build --development                # Debug build (Ada + C with assertions/debug info)
    ./build.py build --release                    # Release build (optimised, checks stripped)
    ./build.py clean                              # Clean both Ada crates and ESP-IDF
    ./build.py clean build                        # Chain: clean then build
    ./build.py build flash monitor                # Build, flash, then open serial monitor
    ./build.py flash                              # Flash firmware to device
    ./build.py monitor                            # Open serial monitor (no build)
    ./build.py build --alr -- -XFOO=bar           # Pass extra arguments to alr
    ./build.py keygen                             # Generate test keypairs (ESP32 + Python)
    ./build.py keygen --psk                       # Generate keypairs with a pre-shared key
    ./build.py build --container                  # Build inside the OCI container
    ./build.py build --container --development    # Dev build in container
    ./build.py build flash monitor --container    # Build, flash, and monitor from container (Linux)
    ./build.py prove                              # Run SPARK proofs only (gold level)
    ./build.py build --no-prove                   # Skip SPARK proofs before building

Flags:
    --development       Debug build for both Ada and C (assertions, ghost checks, -Og)
    --release           Optimised release build for both Ada and C (default)
    --container         Run the build inside the reproducible OCI container
    --no-prove          Skip SPARK proof step during build
    --alr <args...>     Pass extra arguments to alr build/clean commands
    --psk               Include a random 32-byte pre-shared key (keygen only)
"""

import os
import sys
import shutil
import subprocess
from pathlib import Path

# Configuration
SCRIPT_DIR = Path(__file__).parent.absolute()
REPO_ROOT = SCRIPT_DIR.parent
ADA_CRATES = ["wireguard"]  # Single consolidated crate
VALID_COMMANDS = {"build", "clean", "keygen", "prove", "flash", "monitor"}
CONTAINER_IMAGE = "seikan-build"
CONTAINERFILE = SCRIPT_DIR / "Containerfile"


def generate_keypairs(with_psk=False):
    """Generate two X25519 keypairs (ESP32 + Python) and optional PSK.

    Outputs:
      1. Python module at tests/integration/test_keys.py
      2. ESP32 key hex printed to stdout for sdkconfig
    """
    from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey

    esp32_priv = X25519PrivateKey.generate()
    esp32_pub = esp32_priv.public_key().public_bytes_raw()
    esp32_priv_bytes = esp32_priv.private_bytes_raw()

    python_priv = X25519PrivateKey.generate()
    python_pub = python_priv.public_key().public_bytes_raw()
    python_priv_bytes = python_priv.private_bytes_raw()

    psk_bytes = os.urandom(32) if with_psk else bytes(32)

    # ── Write Python module ──────────────────────────────────────────
    keys_file = SCRIPT_DIR / "tests" / "integration" / "test_keys.py"
    lines = [
        '"""Fixed test keypairs for integration testing.',
        "",
        "Auto-generated by build.py keygen — do not edit by hand.",
        '"""',
        "",
        "from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey",
        "",
        "",
        f'ESP32_PRIVATE_HEX = "{esp32_priv_bytes.hex()}"',
        f'ESP32_PUBLIC_HEX  = "{esp32_pub.hex()}"',
        "",
        f'PYTHON_PRIVATE_HEX = "{python_priv_bytes.hex()}"',
        f'PYTHON_PUBLIC_HEX  = "{python_pub.hex()}"',
        "",
        f'PRESHARED_KEY_HEX = "{psk_bytes.hex()}"',
        "",
        "",
        "# ── Convenience helpers ──────────────────────────────────────────",
        "",
        "def esp32_private_key() -> X25519PrivateKey:",
        '    """ESP32 static private key as an X25519PrivateKey object."""',
        "    return X25519PrivateKey.from_private_bytes(bytes.fromhex(ESP32_PRIVATE_HEX))",
        "",
        "",
        "def python_private_key() -> X25519PrivateKey:",
        '    """Python-side static private key as an X25519PrivateKey object."""',
        "    return X25519PrivateKey.from_private_bytes(bytes.fromhex(PYTHON_PRIVATE_HEX))",
        "",
        "",
        "def esp32_public() -> bytes:",
        '    """ESP32 static public key as raw bytes."""',
        "    return bytes.fromhex(ESP32_PUBLIC_HEX)",
        "",
        "",
        "def python_public() -> bytes:",
        '    """Python-side static public key as raw bytes."""',
        "    return bytes.fromhex(PYTHON_PUBLIC_HEX)",
        "",
        "",
        "def preshared_key() -> bytes:",
        '    """Pre-shared key as raw bytes (all-zero if no PSK)."""',
        "    return bytes.fromhex(PRESHARED_KEY_HEX)",
        "",
    ]
    keys_file.write_text("\n".join(lines))
    print(f"  Wrote {keys_file.relative_to(SCRIPT_DIR)}")

    # ── Print ESP32 keys to stdout ───────────────────────────────────
    print("\n" + "=" * 60)
    print("  ESP32 sdkconfig values (paste into sdkconfig or menuconfig)")
    print("=" * 60)
    print(f'CONFIG_WG_STATIC_PRIVATE_KEY="{esp32_priv_bytes.hex()}"')
    print(f'CONFIG_WG_PEER_PUBLIC_KEY="{python_pub.hex()}"')
    if with_psk:
        print(f'CONFIG_WG_PRESHARED_KEY="{psk_bytes.hex()}"')
    else:
        print('CONFIG_WG_PRESHARED_KEY=""')
    print("=" * 60)

    # Also print the Python side for reference
    print("\n  Python-side keys (already saved in test_keys.py):")
    print(f"  Private: {python_priv_bytes.hex()}")
    print(f"  Public:  {python_pub.hex()}")
    print(f"  ESP32 public (peer for Python): {esp32_pub.hex()}")
    if with_psk:
        print(f"  PSK:     {psk_bytes.hex()}")
    print()

    return True


def find_container_runtime():
    """Find podman or docker on PATH. Prefer podman (rootless, daemonless)."""
    for runtime in ("podman", "docker"):
        if shutil.which(runtime):
            return runtime
    return None


def ensure_container_image(runtime):
    """Build the container image if it doesn't already exist."""
    # Check if image exists
    result = subprocess.run(
        [runtime, "image", "exists", CONTAINER_IMAGE],
        capture_output=True,
    )
    if result.returncode == 0:
        return True

    print(f"\n  Container image '{CONTAINER_IMAGE}' not found — building...")
    print(f"  $ {runtime} build -t {CONTAINER_IMAGE} -f Containerfile .")
    result = subprocess.run(
        [runtime, "build", "-t", CONTAINER_IMAGE, "-f", str(CONTAINERFILE), "."],
        cwd=SCRIPT_DIR,
    )
    if result.returncode != 0:
        print("ERROR: Failed to build container image.")
        return False
    return True


def run_in_container(args):
    """Re-invoke build.py inside the OCI container.

    Bind-mounts the repo root at /work so the container has access to
    .git and submodules. Passes through all arguments except --container
    itself.
    """
    runtime = find_container_runtime()
    if runtime is None:
        print("ERROR: Neither podman nor docker found on PATH.")
        print("       Install podman:  sudo dnf install podman")
        sys.exit(1)

    if not ensure_container_image(runtime):
        sys.exit(1)

    # Strip --container from the forwarded args
    forwarded = [a for a in args if a != "--container"]

    # If forwarded args include flash or monitor, pass through /dev for USB
    # serial access (Linux only).
    needs_device = any(a in ("flash", "monitor") for a in forwarded)
    needs_interactive = "monitor" in forwarded

    cmd = [
        runtime, "run", "--rm", "-t",
    ]

    if needs_interactive:
        cmd += ["-i"]

    cmd += ["-v", f"{REPO_ROOT}:/work:Z"]

    if needs_device and sys.platform == "linux":
        cmd += ["--privileged", "-v", "/dev:/dev"]
    elif needs_device:
        print("ERROR: flash/monitor inside the container requires Linux.")
        print("       Run without --container to flash/monitor on this OS.")
        sys.exit(1)

    cmd += [CONTAINER_IMAGE] + forwarded

    print(f"\n  Delegating to container ({runtime})...")
    print(f"  $ {' '.join(cmd)}")
    result = subprocess.run(cmd)
    sys.exit(result.returncode)


def check_idf_path():
    """Verify IDF_PATH environment variable is set."""
    if not os.environ.get("IDF_PATH"):
        print("ERROR: IDF_PATH not set. Run: source /opt/esp-idf/export.sh")
        sys.exit(1)


def run_command(cmd, cwd=None, description=""):
    """Execute a shell command with output streamed to terminal."""
    try:
        if description:
            print(f"\n  {description}...")
        print(f"  $ {cmd}")
        
        result = subprocess.run(
            cmd,
            shell=True,
            cwd=cwd or SCRIPT_DIR,
        )
        
        return result.returncode == 0
    except Exception as e:
        print(f"ERROR: {e}")
        return False


def run_command_interactive(cmd, cwd=None, description=""):
    """Execute a shell command interactively (output to terminal)."""
    try:
        if description:
            print(f"\n{description}...\n")
        
        result = subprocess.run(
            cmd,
            shell=True,
            cwd=cwd or SCRIPT_DIR,
        )
        
        return result.returncode == 0
    except Exception as e:
        print(f"ERROR: {e}")
        return False


def clean_ada_crates(alr_args=""):
    """Clean all Ada crates."""
    print("\n[1/2] Cleaning Ada crates with Alire...")
    all_success = True
    
    for crate in ADA_CRATES:
        crate_dir = SCRIPT_DIR / crate
        cmd = f"alr clean".strip()
        if not run_command(cmd, cwd=crate_dir, description=f"Cleaning {crate}"):
            all_success = False
    
    return all_success


def clean_idf(idf_args=""):
    """Clean ESP-IDF build."""
    print("\n[2/2] Cleaning ESP-IDF firmware...")
    build_dir = SCRIPT_DIR / "build"
    if build_dir.exists():
        # Remove build/ directly — idf.py fullclean refuses to delete a
        # directory it didn't create (e.g. bind-mounted from the host).
        shutil.rmtree(build_dir)
        print("  Removed build/")
    cmd = f"idf.py fullclean {idf_args}".strip()
    return run_command(cmd, description="Cleaning ESP-IDF")


def prove_ada_crates():
    """Run SPARK proofs (gold level) on all Ada crates."""
    print("\n[1/3] Running SPARK proofs (gold level)...")
    all_success = True

    for crate in ADA_CRATES:
        crate_dir = SCRIPT_DIR / crate
        cmd = (
            "alr exec -- gnatprove -P wireguard.gpr"
            " --mode=gold --timeout=5 -j0"
            " -XPLATFORM=esp_idf -XCRYPTO_BACKEND=libsodium"
        )
        if not run_command(cmd, cwd=crate_dir, description=f"Proving {crate}"):
            all_success = False

    return all_success


def build_ada_crates(alr_args="", profile="release"):
    """Build all Ada crates."""
    print("\n[2/3] Building Ada crates with Alire...")
    all_success = True

    for crate in ADA_CRATES:
        crate_dir = SCRIPT_DIR / crate
        cmd = f"alr build --{profile} {alr_args}".strip()
        if not run_command(cmd, cwd=crate_dir, description=f"Building {crate}"):
            all_success = False
    
    return all_success


def build_idf(idf_args="", profile="release"):
    """Build ESP-IDF firmware.
    
    SDKCONFIG_DEFAULTS is only applied when sdkconfig is first generated.
    To handle profile switches we track the active profile in .build_profile
    and delete sdkconfig when it changes, forcing regeneration.
    """
    print("\n[3/3] Building ESP-IDF firmware...")

    # Detect profile switch → delete sdkconfig so defaults are re-applied
    profile_marker = SCRIPT_DIR / ".build_profile"
    previous_profile = profile_marker.read_text().strip() if profile_marker.exists() else None
    if previous_profile != profile:
        sdkconfig = SCRIPT_DIR / "sdkconfig"
        if sdkconfig.exists() and previous_profile is not None:
            print(f"  Profile changed ({previous_profile} → {profile}), reconfiguring...")
            sdkconfig.unlink()
        profile_marker.write_text(profile + "\n")

    if profile == "release":
        defaults = "sdkconfig.defaults;sdkconfig.release"
    else:
        defaults = "sdkconfig.defaults;sdkconfig.development"
    # Append secrets (WiFi credentials, WG keys) if present
    secrets = SCRIPT_DIR / "sdkconfig.secrets"
    if secrets.exists():
        defaults += ";sdkconfig.secrets"
    cmd = f"idf.py -DSDKCONFIG_DEFAULTS='{defaults}' build {idf_args}".strip()
    return run_command(cmd, description="Building firmware")


def execute_command(cmd, alr_args="", idf_args="", psk=False, profile="release",
                    skip_prove=False):
    """Execute a single command."""
    if cmd == "clean":
        return clean_ada_crates(alr_args) and clean_idf(idf_args)
    elif cmd == "prove":
        return prove_ada_crates()
    elif cmd == "build":
        return (
            build_ada_crates(alr_args, profile)
            and (skip_prove or prove_ada_crates())
            and build_idf(idf_args, profile)
        )
    elif cmd == "keygen":
        return generate_keypairs(with_psk=psk)
    elif cmd == "flash":
        return run_command_interactive("idf.py flash", description="Flashing firmware")
    elif cmd == "monitor":
        return run_command_interactive("idf.py monitor", description="Opening serial monitor")
    else:
        return False


def print_header(title):
    """Print a formatted header."""
    print("\n" + "=" * 42)
    print(f"{title.center(42)}")
    print("=" * 42)


def print_footer(success):
    """Print a formatted footer."""
    print("\n" + "=" * 42)
    if success:
        print(f"{'Build Complete!'.center(42)}")
        print(f"{'Firmware: build/VeriGuard.elf'.center(42)}")
    else:
        print(f"{'Build Failed!'.center(42)}")
    print("=" * 42 + "\n")


def main():
    """Main entry point."""
    
    # Two-pass parser: extract flags first, then build command list.
    args = sys.argv[1:]
    
    if not args:
        args = ["build"]

    # If --container is present, delegate to the OCI container immediately
    if "--container" in args:
        run_in_container(args)
        # run_in_container calls sys.exit — we never reach here
    
    # Pass 1: extract flags
    alr_args = ""
    psk_flag = False
    skip_prove = False
    profile = "release"  # default
    command_names = []
    
    i = 0
    while i < len(args):
        arg = args[i]
        
        if arg == "--psk":
            psk_flag = True
            i += 1
        
        elif arg == "--development":
            profile = "development"
            i += 1
        
        elif arg == "--release":
            profile = "release"
            i += 1
        
        elif arg == "--no-prove":
            skip_prove = True
            i += 1
        
        elif arg == "--container":
            # Already handled above; skip if it somehow reaches here
            i += 1
        
        elif arg == "--alr":
            # Collect alr args until a valid command or another flag
            alr_parts = []
            i += 1
            while i < len(args) and args[i] not in VALID_COMMANDS and args[i] not in ("--development", "--release", "--psk", "--no-prove"):
                alr_parts.append(args[i])
                i += 1
            alr_args = " ".join(alr_parts)
        
        elif arg in VALID_COMMANDS:
            command_names.append(arg)
            i += 1
        
        else:
            print(f"ERROR: Unknown argument '{arg}'")
            print(f"\nUsage: {Path(__file__).name} [command ...] [--development|--release] [--container] [--no-prove] [--alr args...]")
            print("\nValid commands: build, clean, keygen, prove, flash, monitor")
            print("\nExamples:")
            print(f"  {Path(__file__).name} build")
            print(f"  {Path(__file__).name} build --development")
            print(f"  {Path(__file__).name} build --container")
            print(f"  {Path(__file__).name} build --no-prove")
            print(f"  {Path(__file__).name} prove")
            print(f"  {Path(__file__).name} build flash monitor")
            print(f"  {Path(__file__).name} monitor")
            print(f"  {Path(__file__).name} clean build --release")
            print(f"  {Path(__file__).name} build --alr -- -XPLATFORM=esp_idf")
            print(f"  {Path(__file__).name} keygen")
            print(f"  {Path(__file__).name} keygen --psk")
            sys.exit(1)
    
    # Pass 2: build command list
    if not command_names:
        command_names = ["build"]
    
    commands = [(cmd, alr_args, "") for cmd in command_names]
    
    # Only require IDF_PATH for build/clean/flash/monitor (not keygen)
    needs_idf = any(cmd[0] in ("build", "clean", "flash", "monitor") for cmd in commands)
    if needs_idf:
        check_idf_path()
    
    # Determine action description
    action = " → ".join(cmd[0] for cmd in commands)
    extra = f" [{profile}]"
    
    print_header(f"VeriGuard {action.title()}{extra}")
    
    # Execute commands in sequence
    success = True
    for cmd, alr_args, idf_args in commands:
        if not execute_command(cmd, alr_args, idf_args, psk=psk_flag,
                              profile=profile, skip_prove=skip_prove):
            success = False
            break
    
    print_footer(success)
    
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
